name: "Flake Update"
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:
jobs:
   update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: configure git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: perform flake update for amplify
      run: |
        nix flake update
        nix build
      working-directory: ./amplify
    - run: |
        git add .
        git commit -m "Flake Update: Amplify" && git push origin || echo "nothing to do"
    - name: perform flake update for project pw
      run: |
        nix flake update
        nix build
      working-directory: ./projects/pw
    - run: |
        git add .
        git commit -m "Flake Update: Pw" && git push origin || echo "nothing to do"
    - name: perform flake update for zwift
      run: |
        nix flake update
        nix build
      working-directory: ./zwift
    - run: |
        git add .
        git commit -m "Flake Update: Zwift" && git push origin || echo "nothing to do"
